const { createClient } = require('@supabase/supabase-js');
const bcrypt = require('bcryptjs');
require('dotenv').config();

async function seedAdminUser() {
  const supabaseUrl = process.env.SUPABASE_URL;
  const supabaseKey = process.env.SUPABASE_SECRET_KEY;

  if (!supabaseUrl || !supabaseKey) {
    console.error('❌ Missing SUPABASE_URL or SUPABASE_SECRET_KEY in .env file');
    process.exit(1);
  }

  const client = createClient(supabaseUrl, supabaseKey, {
    auth: { persistSession: false, autoRefreshToken: false }
  });

  console.log('🔐 Creating default admin user...');

  // Admin credentials
  const adminEmail = 'admin@kael.com';
  const adminPassword = 'admin123';  // Changed to match documentation
  const adminDisplayName = 'Super Admin';
  const adminRole = 'super_admin';

  try {
    // Hash password
    const passwordHash = await bcrypt.hash(adminPassword, 10);

    // Check if admin already exists
    const { data: existing } = await client
      .from('aggregator_users')
      .select('email')
      .eq('email', adminEmail)
      .maybeSingle();

    if (existing) {
      console.log('⚠️  Admin user already exists. Updating password...');
      
      // Update existing admin
      const { error: updateError } = await client
        .from('aggregator_users')
        .update({ 
          password_hash: passwordHash,
          display_name: adminDisplayName,
          role: adminRole,
          is_active: true,
          updated_at: new Date().toISOString()
        })
        .eq('email', adminEmail);

      if (updateError) throw updateError;
      
      console.log('✅ Admin user updated successfully!');
    } else {
      // Create new admin (UUID auto-generated by database)
      const { error: insertError } = await client
        .from('aggregator_users')
        .insert({
          email: adminEmail,
          display_name: adminDisplayName,
          role: adminRole,
          password_hash: passwordHash,
          is_active: true
        });

      if (insertError) throw insertError;
      
      console.log('✅ Admin user created successfully!');
    }

    console.log('');
    console.log('═══════════════════════════════════════════════════════');
    console.log('  📋 ADMIN CREDENTIALS');
    console.log('═══════════════════════════════════════════════════════');
    console.log(`  Email:    ${adminEmail}`);
    console.log(`  Password: ${adminPassword}`);
    console.log('═══════════════════════════════════════════════════════');
    console.log('');
    console.log('⚠️  IMPORTANT: Change the password after first login!');
    console.log('');

  } catch (error) {
    console.error('❌ Error seeding admin user:', error.message);
    process.exit(1);
  }
}

seedAdminUser();
